name: Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  Test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'zulu'
      - name: Setup Clojure
        uses: DeLaGuardo/setup-clojure@3.4
        with:
          cli: 1.10.3.855

      - name: Cache jars
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: maven-${{ hashFiles('project.clj') }}
          restore-keys: |
            maven-

      - name: Server tests
        run: clojure -M:test

      - name: Client compilation check
        run: clojure -M:cljs -co ./cljs_prod.edn --compile
